// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/http;

public type Locale string;

public type StoreKeyReference record {
    *KeyReference;
    ReferenceTypeId typeId;
    string 'key;
};

# OAuth2 Client Credentials Grant Configs
public type OAuth2ClientCredentialsGrantConfig record {|
    *http:OAuth2ClientCredentialsGrantConfig;
    # Token URL
    string tokenUrl = "https://auth.us-central1.gcp.commercetools.com/oauth/token";
|};

public type Address record {
    *BaseAddress;
    CountryCode country?;
    string lastName?;
    string city?;
    string postalCode?;
    string title?;
    string building?;
    string streetName?;
    string company?;
    string id?;
    string state?;
    string department?;
    string fax?;
    string 'key?;
    string email?;
    string pOBox?;
    string streetNumber?;
    CustomFields custom?;
    string mobile?;
    string externalId?;
    string additionalAddressInfo?;
    string firstName?;
    string phone?;
    string additionalStreetInfo?;
    string salutation?;
    string region?;
    string apartment?;
};

public type KeyReference record {
    ReferenceTypeId typeId;
    string 'key;
};

public type Customer record {
    *BaseResource;
    string lastName?;
    Address[] addresses;
    string lastModifiedAt;
    string companyName?;
    string vatId?;
    string title?;
    Locale locale?;
    string[] shippingAddressIds;
    boolean isEmailVerified;
    string createdAt;
    string password?;
    string id;
    AuthenticationMode authenticationMode;
    string 'key?;
    string email;
    CustomerGroupReference customerGroup?;
    StoreKeyReference[] stores;
    LastModifiedBy lastModifiedBy?;
    CustomFields custom?;
    string externalId?;
    string dateOfBirth?;
    CustomerGroupAssignment[] customerGroupAssignments;
    string customerNumber?;
    string defaultShippingAddressId?;
    string[] billingAddressIds;
    int version;
    string defaultBillingAddressId?;
    string firstName?;
    CreatedBy createdBy?;
    string middleName?;
    string salutation?;
};

public type RoundingMode "HalfEven"|"HalfUp"|"HalfDown";

public type FieldDefinition record {
    string name;
    TypeTextInputHint inputHint?;
    LocalizedString label;
    FieldType 'type;
    boolean required;
};

public type BusinessUnitConfiguration record {
    AssociateRoleKeyReference myBusinessUnitAssociateRoleOnCreation?;
    BusinessUnitConfigurationStatus myBusinessUnitStatusOnCreation;
};

public type CustomerGroupAssignment record {
    CustomerGroupReference customerGroup;
};

public type SearchIndexingConfiguration record {
    SearchIndexingConfigurationValues businessUnits?;
    SearchIndexingConfigurationValues productsSearch?;
    SearchIndexingConfigurationValues orders?;
    SearchIndexingConfigurationValues customers?;
    SearchIndexingConfigurationValues products?;
};

public type SearchIndexingConfigurationStatus "Activated"|"Deactivated"|"Indexing";

public type CurrencyCode string;

public type BusinessUnitConfigurationStatus "Active"|"Inactive";

public type ResourceTypeId "address"|"asset"|"approval-flow"|"approval-rule"|"associate-role"|"business-unit"|"cart-discount"|"category"|"channel"|"customer"|"customer-group"|"custom-line-item"|"discount-code"|"inventory-entry"|"line-item"|"order"|"order-edit"|"order-delivery"|"order-parcel"|"order-return-item"|"payment"|"payment-interface-interaction"|"payment-method"|"payment-method-info"|"product-price"|"product-selection"|"product-tailoring"|"quote"|"reservation"|"review"|"recurring-order"|"shipping"|"shipping-method"|"shopping-list"|"shopping-list-text-line-item"|"standalone-price"|"store"|"transaction";

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # Configurations related to client authentication
    OAuth2ClientCredentialsGrantConfig auth;
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};

public type CreatedBy record {
    *ClientLogging;
    string anonymousId?;
    string clientId?;
    string externalUserId?;
    Attribution attributedTo?;
    CustomerReference associate?;
    CustomerReference customer?;
};

public type ShoppingListsConfiguration record {
    int deleteDaysAfterLastModification;
};

public type CustomerGroup record {
    *BaseResource;
    string createdAt;
    string lastModifiedAt;
    CreatedBy createdBy?;
    LastModifiedBy lastModifiedBy?;
    CustomFields custom?;
    string name;
    string id;
    int version;
    string 'key?;
};

public type Attribution record {
    string clientId?;
    AttributionSource 'source;
};

public type DiscountsConfiguration record {
    DiscountCombinationMode discountCombinationMode;
};

public type AuthenticationMode "Password"|"ExternalAuth";

public type ShippingRateInputType record {
    ShippingRateTierType 'type;
};

public type Project record {
    ExternalOAuth externalOAuth?;
    ShoppingListsConfiguration shoppingLists?;
    Locale[] languages;
    SearchIndexingConfiguration searchIndexing?;
    CountryCode[] countries;
    InventoryConfiguration inventory;
    int version;
    string trialUntil?;
    ProductCatalogModel productCatalogModel?;
    ShippingRateInputType shippingRateInputType?;
    string createdAt;
    BusinessUnitConfiguration businessUnits?;
    CartsConfiguration carts;
    DiscountsConfiguration discounts;
    string name;
    MessagesConfiguration messages;
    string 'key;
    CurrencyCode[] currencies;
};

public type CustomFields record {
    TypeReference 'type;
    FieldContainer fields;
};

public type CustomerReference record {
    *Reference;
    Customer obj?;
    ReferenceTypeId typeId;
    string id;
};

public type ShippingRateTierType "CartValue"|"CartClassification"|"CartScore";

public type SearchIndexingConfigurationValues record {
    string lastModifiedAt?;
    LastModifiedBy lastModifiedBy?;
    SearchIndexingConfigurationStatus status?;
};

public type AssociateRoleKeyReference record {
    *KeyReference;
    ReferenceTypeId typeId;
    string 'key;
};

public type LastModifiedBy record {
    *ClientLogging;
    string anonymousId?;
    string clientId?;
    string externalUserId?;
    Attribution attributedTo?;
    CustomerReference associate?;
    CustomerReference customer?;
};

public type DiscountCombinationMode "BestDeal"|"Stacking";

public type LocalizedString record {|
    string...;
|};

public type ProjectUpdate record {
    int version;
    ProjectUpdateAction[] actions;
};

public type AttributionSource "Import"|"Export";

public type CustomerGroupReference record {
    *Reference;
    CustomerGroup obj?;
    ReferenceTypeId typeId;
    string id;
};

public type TypeReference record {
    *Reference;
    Type obj?;
    ReferenceTypeId typeId;
    string id;
};

public type ProductCatalogModel "Classic"|"InMigration"|"Modular";

public type CountryCode string;

public type FieldContainer record {|
    string...;
|};

public type ExternalOAuth record {
    string authorizationHeader;
    string url;
};

public type TypeTextInputHint "SingleLine"|"MultiLine";

public type CartsConfiguration record {
    RoundingMode taxRoundingMode?;
    boolean countryTaxRateFallbackEnabled?;
    int deleteDaysAfterLastModification;
    RoundingMode priceRoundingMode?;
};

public type Reference record {
    ReferenceTypeId typeId;
    string id;
};

public type ClientLogging record {
    string anonymousId?;
    string clientId?;
    string externalUserId?;
    CustomerReference associate?;
    CustomerReference customer?;
};

public type BaseResource record {
    string createdAt;
    string lastModifiedAt;
    string id;
    int version;
};

public type ProjectUpdateAction record {
    string action;
};

public type ReferenceTypeId "approval-flow"|"approval-rule"|"associate-role"|"attribute-group"|"business-unit"|"cart"|"cart-discount"|"category"|"channel"|"customer"|"customer-email-token"|"customer-group"|"customer-password-token"|"direct-discount"|"discount-code"|"discount-group"|"extension"|"inventory-entry"|"key-value-document"|"mcp-server"|"order"|"order-edit"|"payment-method"|"payment"|"product"|"product-discount"|"product-price"|"product-selection"|"product-tailoring"|"product-type"|"quote"|"quote-request"|"recurrence-policy"|"recurring-order"|"reservation"|"review"|"shipping-method"|"shopping-list"|"staged-quote"|"standalone-price"|"state"|"store"|"subscription"|"tax-category"|"type"|"variant"|"zone";

public type InventoryConfiguration record {
    boolean releaseExpiredReservations;
    int:Signed32 reservationExpirationInMinutes?;
};

public type MessagesConfiguration record {
    int:Signed32 deleteDaysAfterCreation?;
    boolean enabled;
};

public type BaseAddress record {
    CountryCode country;
    string lastName?;
    string city?;
    string postalCode?;
    string title?;
    string building?;
    string streetName?;
    string company?;
    string id?;
    string state?;
    string department?;
    string fax?;
    string 'key?;
    string email?;
    string pOBox?;
    string streetNumber?;
    string mobile?;
    string externalId?;
    string additionalAddressInfo?;
    string firstName?;
    string phone?;
    string additionalStreetInfo?;
    string salutation?;
    string region?;
    string apartment?;
};

public type FieldType record {
    string name;
};

public type Type record {
    *BaseResource;
    string createdAt;
    string lastModifiedAt;
    CreatedBy createdBy?;
    LastModifiedBy lastModifiedBy?;
    LocalizedString name;
    LocalizedString description?;
    FieldDefinition[] fieldDefinitions;
    string id;
    int version;
    string 'key;
    ResourceTypeId[] resourceTypeIds;
};
